/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exameninfra;

import java.awt.GridLayout;
import java.awt.LayoutManager;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author AlexanderDM
 */
public class MainMemory extends javax.swing.JFrame {

    /**
     * Creates new form MainMemory
     */
    public MainMemory() {
        initComponents();
    }
    int cantFrames;
    
    public void crearFrames(int cantMemoria, int tamano_frames){
        cantFrames = cantMemoria/tamano_frames;
        System.out.println("Frames creados: "+cantFrames);
        for(int i =0;i<cantFrames;i++){
            JPanel pnl = new JPanel();
            pnl.setBounds(5, 5, 45, 45);
            pnl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));
            JLabel lblFrame = new JLabel(""+i);
            JLabel lblProceso = new JLabel("");
            JLabel lblPagina = new JLabel("");
            pnl.add(lblFrame);
            pnl.add(lblProceso);
            pnl.add(lblPagina);
            lblFrame.setLocation(2, 2);
            lblProceso.setLocation(2, 18);
            lblFrame.setLocation(2, 33);
            pnlPrincipal.add(pnl);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlControl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualización de Memoria Principal");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memoria Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(707, 423));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlControl.setBackground(new java.awt.Color(255, 255, 255));
        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMemory mm = new MainMemory();
                mm.setVisible(true);
                mm.crearFrames(64, 4);
                //mm.jScrollPaneFrames.add(new pnlFrame());
                /*
                for (int i = 0; i < 25; i++) {                    
                    javax.swing.JLabel lblPage = new javax.swing.JLabel();
                    javax.swing.JLabel lblFrame = new javax.swing.JLabel();
                    javax.swing.JLabel lblProceso = new javax.swing.JLabel();
                    lblPage.setText("Pg");
                    lblFrame.setText("F_"+i);
                    lblProceso.setText("P");

                    javax.swing.JPanel p = new javax.swing.JPanel();                    
                    //lblFrame.setBounds(5, 3, 60, 23);
                    //lblFrame.
                    //lblPage.setBounds(5, 23, 60, 23);
                    //lblProceso.setBounds(5, 43, 60, 23);
                    //p.add(lblFrame);
                    p.add(lblFrame);
                    p.add(lblProceso);
                    p.add(lblPage);
                    p.setVisible(true);
                    //p.setLayout(new );
                    //p.setLayout(new GridLayout(3, 1, 10, 10));
                    p.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));
                    //p.setMinimumSize(new java.awt.Dimension(52, 62));
                    //p.setBounds(5, 5, 80, 90);
                    p.setSize(80, 90);
                    
                    //mm.jScrollPaneFrames.add(p);
                    //mm.add(p);
                    
                    mm.pnlPrincipal.add(p);
                    //mm.jScrollPaneFrames.add(p);                    
                }
                */

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnlControl;
    public javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
